import type {
  DefaultSharedCoreModuleContext,
  LangiumCoreServices,
  LangiumSharedCoreServices,
  Module,
  PartialLangiumCoreServices,
} from 'langium';
import {
  EmptyFileSystem,
  createDefaultCoreModule,
  createDefaultSharedCoreModule,
  inject,
} from 'langium';
import { CommonValueConverter } from '../common/valueConverter.js';
import { MermaidGeneratedSharedModule, TubemapGeneratedModule } from '../generated/module.js';
import { TubemapTokenBuilder } from './tokenBuilder.js';

/**
 * Declaration of `Tubemap` services.
 */
interface TubemapAddedServices {
  parser: {
    TokenBuilder: TubemapTokenBuilder;
    ValueConverter: CommonValueConverter;
  };
}

/**
 * Union of Langium default services and `Tubemap` services.
 */
export type TubemapServices = LangiumCoreServices & TubemapAddedServices;

/**
 * Dependency injection module that overrides Langium default services and
 * contributes the declared `Tubemap` services.
 */
export const TubemapModule: Module<
  TubemapServices,
  PartialLangiumCoreServices & TubemapAddedServices
> = {
  parser: {
    TokenBuilder: () => new TubemapTokenBuilder(),
    ValueConverter: () => new CommonValueConverter(),
  },
};

/**
 * Create the full set of services required by Langium.
 *
 * First inject the shared services by merging two modules:
 *  - Langium default shared services
 *  - Services generated by langium-cli
 *
 * Then inject the language-specific services by merging three modules:
 *  - Langium default language-specific services
 *  - Services generated by langium-cli
 *  - Services specified in this file
 * @param context - Optional module context with the LSP connection
 * @returns An object wrapping the shared services and the language-specific services
 */
export function createTubemapServices(context: DefaultSharedCoreModuleContext = EmptyFileSystem): {
  shared: LangiumSharedCoreServices;
  Tubemap: TubemapServices;
} {
  const shared: LangiumSharedCoreServices = inject(
    createDefaultSharedCoreModule(context),
    MermaidGeneratedSharedModule
  );
  const Tubemap: TubemapServices = inject(
    createDefaultCoreModule({ shared }),
    TubemapGeneratedModule,
    TubemapModule
  );
  shared.ServiceRegistry.register(Tubemap);
  return { shared, Tubemap };
}
